return {
  "nvim-tree/nvim-tree.lua",
  config = function ()
    vim.keymaps.set("n", "<leader>n", ":NvimTreeToggle<CR>" )

    require("nvim-tree").setup({
      view = { adaptive_size = true, side = "left" },
      update_focused_file = { enable = true },

      on_attach = function (bufnr)
        local api = require("nvim-tree.api")

        local function opts(desc)
          return { desc = "nvim-tree: " .. desc, buffer = bufnr, noremap = true, silent = true, nowait = true }
        end

        vim.keymaps.set("n", "<C-]>", api.tree.change_root_to_node, opts("CD"))
        vim.keymaps.set("n", "<C-e>", api.node.open.replace_tree_buffer, opts("Open: In Place"))
        vim.keymaps.set("n", "<C-k>", api.node.show_info_popup, opts("Info"))
        vim.keymaps.set("n", "<C-r>", api.fs.rename_sub, opts("Rename: Omit Filename"))
        vim.keymaps.set("n", "<C-t>", api.node.open.tab, opts("Open: New Tab"))
        vim.keymaps.set("n", "<C-v>", api.node.open.vertical, opts("Open: Vertical Split"))
        vim.keymaps.set("n", "<C-x>", api.node.open.horizontal, opts("Open: Horizontal Split"))
        vim.keymaps.set("n", "<BS>",  api.node.navigate.parent_close, opts("Close Directory"))
        vim.keymaps.set("n", "<CR>",  api.node.open.edit, opts("Open"))
        vim.keymaps.set("n", "<Tab>", api.node.open.preview, opts("Open Preview"))
        vim.keymaps.set("n", ">", api.node.navigate.sibling.next, opts("Next Sibling"))
        vim.keymaps.set("n", "<", api.node.navigate.sibling.prev, opts("Previous Sibling"))
        vim.keymaps.set("n", ".", api.node.run.cmd, opts("Run Command"))
        vim.keymaps.set("n", "-", api.tree.change_root_to_parent, opts("Up"))
        vim.keymaps.set("n", "a", api.fs.create, opts("Create"))
        vim.keymaps.set("n", "bmv", api.marks.bulk.move, opts("Move Bookmarked"))
        vim.keymaps.set("n", "B", api.tree.toggle_no_buffer_filter, opts("Toggle No Buffer"))
        vim.keymaps.set("n", "c", api.fs.copy.node, opts("Copy"))
        vim.keymaps.set("n", "C", api.tree.toggle_git_clean_filter, opts("Toggle Git Clean"))
        vim.keymaps.set("n", "[c", api.node.navigate.git.prev, opts("Prev Git"))
        vim.keymaps.set("n", "]c", api.node.navigate.git.next, opts("Next Git"))
        vim.keymaps.set("n", "d", api.fs.remove, opts("Delete"))
        vim.keymaps.set("n", "D", api.fs.trash, opts("Trash"))
        vim.keymaps.set("n", "E", api.tree.expand_all, opts("Expand All"))
        vim.keymaps.set("n", "e", api.fs.rename_basename, opts("Rename: Basename"))
        vim.keymaps.set("n", "]e", api.node.navigate.diagnostics.next, opts("Next Diagnostic"))
        vim.keymaps.set("n", "[e", api.node.navigate.diagnostics.prev, opts("Prev Diagnostic"))
        vim.keymaps.set("n", "F", api.live_filter.clear, opts("Clean Filter"))
        vim.keymaps.set("n", "f", api.live_filter.start, opts("Filter"))
        vim.keymaps.set("n", "g?", api.tree.toggle_help, opts("Help"))
        vim.keymaps.set("n", "gy", api.fs.copy.absolute_path, opts("Copy Absolute Path"))
        vim.keymaps.set("n", "H", api.tree.toggle_hidden_filter, opts("Toggle Dotfiles"))
        vim.keymaps.set("n", "I", api.tree.toggle_gitignore_filter, opts("Toggle Git Ignore"))
        vim.keymaps.set("n", "J", api.node.navigate.sibling.last, opts("Last Sibling"))
        vim.keymaps.set("n", "K", api.node.navigate.sibling.first, opts("First Sibling"))
        vim.keymaps.set("n", "m", api.marks.toggle, opts("Toggle Bookmark"))
        vim.keymaps.set("n", "o", api.node.open.edit, opts("Open"))
        vim.keymaps.set("n", "O", api.node.open.no_window_picker, opts("Open: No Window Picker"))
        vim.keymaps.set("n", "p", api.fs.paste, opts("Paste"))
        vim.keymaps.set("n", "P", api.node.navigate.parent, opts("Parent Directory"))
        vim.keymaps.set("n", "q", api.tree.close, opts("Close"))
        vim.keymaps.set("n", "r", api.fs.rename, opts("Rename"))
        vim.keymaps.set("n", "R", api.tree.reload, opts("Refresh"))
        vim.keymaps.set("n", "s", api.node.run.system, opts("Run System"))
        vim.keymaps.set("n", "S", api.tree.search_node, opts("Search"))
        vim.keymaps.set("n", "U", api.tree.toggle_custom_filter, opts("Toggle Hidden"))
        vim.keymaps.set("n", "W", api.tree.collapse_all, opts("Collapse"))
        vim.keymaps.set("n", "x", api.fs.cut, opts("Cut"))
        vim.keymaps.set("n", "y", api.fs.copy.filename, opts("Copy Name"))
        vim.keymaps.set("n", "Y", api.fs.copy.relative_path, opts("Copy Relative Path"))
        vim.keymaps.set("n", "<2-LeftMouse>", api.node.open.edit, opts("Open"))
        vim.keymaps.set("n", "<2-RightMouse>", api.tree.change_root_to_node, opts("CD"))
        vim.keymaps.set("n", "u", api.tree.change_root_to_parent, opts("Up"))
        vim.keymaps.set("n", "v", api.node.open.vertical, opts("Open: Vertical Split"))
        vim.keymaps.set("n", "x", api.node.open.horizontal, opts("Open: Horizontal Split"))
        vim.keymaps.set("n", "t", api.node.open.tab, opts("Open: New Tab"))
        vim.keymaps.set("n", "r", api.fs.rename_sub, opts("Rename: Omit Filename"))
      end
    })
  end
}
